/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseDashboardCard: typeof import('./src/components/exercise/BaseDashboardCard.vue')['default']
    ClassBind: typeof import('./src/components/basic/practice/ClassBind.vue')['default']
    ExAxios: typeof import('./src/components/basic/practice/exAxios.vue')['default']
    ExComputed: typeof import('./src/components/basic/practice/exComputed.vue')['default']
    ExDafaultSlotChild: typeof import('./src/components/basic/practice/slot/exDafaultSlotChild.vue')['default']
    ExDeepWatch: typeof import('./src/components/basic/practice/exDeepWatch.vue')['default']
    ExDefaultSlotParent: typeof import('./src/components/basic/practice/slot/exDefaultSlotParent.vue')['default']
    ExLifeCycleHookChild: typeof import('./src/components/basic/practice/exLifeCycleHookChild.vue')['default']
    ExLifeCycleHookParents: typeof import('./src/components/basic/practice/exLifeCycleHookParents.vue')['default']
    ExNamedSlotChild: typeof import('./src/components/basic/practice/slot/exNamedSlotChild.vue')['default']
    ExNamedSlotParent: typeof import('./src/components/basic/practice/slot/exNamedSlotParent.vue')['default']
    ExPropsEmitsChild: typeof import('./src/components/basic/practice/exPropsEmitsChild.vue')['default']
    ExPropsEmitsParent: typeof import('./src/components/basic/practice/exPropsEmitsParent.vue')['default']
    ExReactive: typeof import('./src/components/basic/practice/exReactive.vue')['default']
    ExRef: typeof import('./src/components/basic/practice/exRef.vue')['default']
    ExRun: typeof import('./src/components/basic/practice/exRun.vue')['default']
    ExScopedSlotChild: typeof import('./src/components/basic/practice/slot/exScopedSlotChild.vue')['default']
    ExScopedSlotParent: typeof import('./src/components/basic/practice/slot/exScopedSlotParent.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    Practice: typeof import('./src/components/Practice.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SampleOne: typeof import('./src/components/basic/practice/SampleOne.vue')['default']
    SearchBar: typeof import('./src/components/exercise/SearchBar.vue')['default']
    StyleBind: typeof import('./src/components/basic/practice/StyleBind.vue')['default']
    ThemeToggler: typeof import('./src/components/exercise/ThemeToggler.vue')['default']
    UApp: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UBadge: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Badge.vue')['default']
    UButton: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UInput: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UnitToggler: typeof import('./src/components/exercise/UnitToggler.vue')['default']
    USelect: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Select.vue')['default']
    VBind: typeof import('./src/components/basic/practice/vBind.vue')['default']
    VHtml: typeof import('./src/components/basic/practice/vHtml.vue')['default']
    VText: typeof import('./src/components/basic/practice/vText.vue')['default']
    WeatherCard: typeof import('./src/components/exercise/weatherCard.vue')['default']
    WeatherMap: typeof import('./src/components/exercise/WeatherMap.vue')['default']
    WeatherMockup: typeof import('./src/components/exercise/WeatherMockup.vue')['default']
    WeatherParent: typeof import('./src/components/exercise/weatherParent.vue')['default']
  }
}
